### ISSUE TITLE
Does not run on windows

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/paraview-lite#2]
Tried to get it running on Windows 10:
```
win_delay_load_hook.cc
c:\users\danie\appdata\roaming\npm\node_modules\paraview-lite\node_modules\canvas\src\canvas.h(19): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "cairo.h":
No such file or directory (Quelldatei wird kompiliert ..\src\init.cc) [C:\Users\danie\AppData\Roaming\npm\node_modules\paraview-lite\node_modules\canvas\build\canvas.vcxproj]
c:\users\danie\appdata\roaming\npm\node_modules\paraview-lite\node_modules\canvas\src\canvas.h(19): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "cairo.h":
No such file or directory

 ....

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\danie\AppData\Roaming\npm\node_modules\paraview-lite\node_modules\canvas
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jourdain** [comment]
You mean you can not install the project for development on Windows.
Since running it is the same as running ParaView and that work.

**Comment by jourdain** [comment]
You can follow the instruction on how to enable canvas on your system by following instructions available here:
https://www.npmjs.com/package/canvas

**Comment by doczoidberg** [comment]
I need to build it because it isn't bundled with paraview 5.6 RC2

**Comment by jourdain** [comment]
It is bundle in the nightly version meaning the future RC3.

**Comment by doczoidberg** [comment]
ah ok, thank you. Nice to see paraview lite based on vue
