### ISSUE TITLE
lite_protocols.py import issue

### ISSUE THREAD

**Issue by Prags21** [Kitware/paraview-lite#9]
Throws following error:

Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.8.0-Windows-Python3.7-msvc2015-64bit\share\paraview-5.8\web\lite\server\lite_protocols.py", line 13, in <module>
    from vtkmodules.vtkPVClientServerCoreRendering import vtkPVRenderView
ModuleNotFoundError: No module named 'vtkmodules.vtkPVClientServerCoreRendering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "share\paraview-5.8\web\lite\server\pvw-lite.py", line 94, in <module>
    import lite_protocols as local_protocols
  File "C:\Program Files\ParaView 5.8.0-Windows-Python3.7-msvc2015-64bit\share\paraview-5.8\web\lite\server\lite_protocols.py", line 16, in <module>
    from paraview.modules.vtkPVClientServerCoreRendering import vtkPVRenderView
ModuleNotFoundError: No module named 'paraview.modules.vtkPVClientServerCoreRendering'

**Comment by jourdain** [comment]
That was actually solved in the 1.4.4 version of ParaView Lite which will be available in PV 5.8.1
